ekf_filter_node:
  ros__parameters:
    frequency: 50.0
    sensor_timeout: 0.5
    two_d_mode: true

    publish_tf: true
    # map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # -------------------------
    # Wheel odometry input
    # -------------------------
    odom0: /wheel/odometry
    odom0_queue_size: 20
    odom0_differential: false
    odom0_relative: false

    # Fuse x, y, yaw and vx, vy, wz from wheel odom (tune as needed)
    # State order:
    # [x, y, z,
    #  roll, pitch, yaw,
    #  vx, vy, vz,
    #  vroll, vpitch, vyaw,
    #  ax, ay, az]

    odom0_config: [true,  true,  false,
                   false, false, true,
                   true,  true,  false,
                   false, false, true,
                   false, false, false]

    # odom0_config: [false, false, false,
    #            false, false, false,
    #            true,  false, false,
    #            false, false, true,
    #            false, false, false]


    # -------------------------
    # XSens IMU (orientation only)
    # -------------------------
    imu0: /xsens_imu
    imu0_queue_size: 50
    imu0_differential: false
    imu0_relative: true
    imu0_remove_gravitational_acceleration: false

    # Fuse only yaw orientation from IMU (2D)
    
    imu0_config: [false, false, false,
                  false, false, true,
                  false, false, false,
                  false, false, false,
                  false, false, false]

    
 

