slam_toolbox:
  ros__parameters:
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan_fullframe
    use_sim_time: false

    mode: mapping
    use_scan_matching: true
    use_scan_barycenter: true

    minimum_travel_distance: 0.05
    minimum_travel_heading: 0.05

    resolution: 0.05
    max_laser_range: 3.6

    minimum_time_interval: 0.1
    map_update_interval: 1.0
    transform_publish_period: 0.02

    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01

    do_loop_closing: true
    loop_match_minimum_chain_size: 5

    tf_buffer_duration: 30.0
    transform_timeout: 1.0

    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    solver_num_threads: 8
